### PR TITLE
Add support for PHP 8.2, Drop support for PHP 7.4

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

Also drops test that are < 8.0 specific

### CODE REVIEW

**Comment by gsteel** [comment]
Needs https://github.com/laminas/laminas-stratigility/pull/33

**Comment by Ocramius** [comment]
@gsteel done and in release

**Comment by gsteel** [comment]
Thanks @Ocramius :)

**Review by Ocramius — APPROVED** [review]
:ship:

**Pull request merged**
